---
abstract: 'Call asynchronous APIs synchronously'
author:
  - 'Rebecca Turner <becca@referencethis.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-Capture
requires:
  AnyEvent: 0
  Sub::Exporter: 0
resources:
  bugtracker: https://github.com/iarna/AnyEvent-Capture/issues
  homepage: https://github.com/iarna/AnyEvent-Capture
  repository: https://github.com/iarna/AnyEvent-Capture.git
version: 0.1.0
